In [3]:
import pandas as pd
from plotnine import *
from mizani.formatters import date_format

# based on economical region, the following rows are chosen.
'''
 'World': 'WLD'
 'North America': 'NAC',
 'East Asia & Pacific': 'EAS',
 'Europe & Central Asia': 'ECS',
 'Latin America & Caribbean': 'LCN',
 'Sub-Saharan Africa': 'SSF',
             'Africa Eastern and Southern': 'AFE'
             'Africa Western and Central': 'AFW'
 'South Asia': 'SAS',            
 'Middle East, North Africa, Afghanistan & Pakistan': 'MEA',


 metrics used are considered are: unemployment, inflation, gdp growth
    interest rate, exchange rate, debt ratio are not suitable for regional comparison


three techinques used for corrlatoin:
Time Series A & B → Do they have a time lag? → Yes → CCF (Cross-Correlation)
                                    
'''

"\n 'World': 'WLD'\n 'North America': 'NAC',\n 'East Asia & Pacific': 'EAS',\n 'Europe & Central Asia': 'ECS',\n 'Latin America & Caribbean': 'LCN',\n 'Sub-Saharan Africa': 'SSF',\n             'Africa Eastern and Southern': 'AFE'\n             'Africa Western and Central': 'AFW'\n 'South Asia': 'SAS',            \n 'Middle East, North Africa, Afghanistan & Pakistan': 'MEA',\n\n\n metrics used are considered are: unemployment, inflation, gdp growth\n    interest rate, exchange rate, debt ratio are not suitable for regional comparison\n\n\nthree techinques used for corrlatoin:\nTime Series A & B → Do they have a time lag? → Yes → CCF (Cross-Correlation)\n                                    \n"

In [4]:
# define base path and columns/rows of interest
base_path = "./Task2"
mycols = ['Country Name', 'Country Code']
yr = 2013
while yr < 2025:
    mycols.append(str(yr))
    yr += 1
myrows = ['WLD','NAC','EAS','ECS','LCN','SSF','SAS','MEA']

In [5]:
# Deciding region and plot GDP
df = pd.read_csv(
    base_path + r"\data\GDP.csv"
)
#df.isna().sum().to_csv(base_path + "./nan_GDP.csv")
df_s = df.loc[:, mycols]
# Summing up GDP of countries in the same region
df_s = (
    df_s
    .groupby("Country Code", as_index=False)
    .sum(numeric_only=True)
)
df_s = df_s[df_s['Country Code'].isin(myrows)]
df_s = df_s.reset_index(drop=True).T  # transpose
df_s = df_s.reset_index().rename(columns={'index': 'Year'}) # reset index and rename
df_s.columns = df_s.iloc[0]                                 # set first row as header
df_s.rename(columns={'Country Code': 'Year'}, inplace=True) # rename column since transposing
df_s = df_s[1:]                                # remove first row since it is now header
df_s = df_s.apply(pd.to_numeric, errors='coerce')
years = df_s['Year'].tolist() # get list of years for x-axis
# Melt the dataframe for ggplot
df_GDP_long = df_s.melt(id_vars='Year', var_name='Region', value_name='GDP')
# color code used in the project
colors = [
    "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728",
    "#9467bd", "#8c564b", "#e377c2", "#7f7f7f",
    "#bcbd22", "#17becf", "#aec7e8", "#ffbb78",
    "#98df8a", "#ff9896", "#c5b0d5", "#c49c94",
    "#f7b6d2", "#c7c7c7", "#dbdb8d", "#9edae5"
]
p =(
    ggplot(df_GDP_long, aes(x='Year', y='GDP', color='Region'))
    + geom_line()
    + geom_point()
    + scale_color_manual(values=colors[:len(df_GDP_long['Region'].unique())])
    + scale_x_continuous(breaks=years)
    + scale_y_continuous(labels=lambda l: [f"{v:.2e}" for v in l])
    + labs(title="GDP for different regions", x="Year", y="GDP")
    + theme(axis_text_x=element_text(rotation=45, ha='right'))
)
p.save(base_path + r"\img\GDP_regions.png", dpi=300, limitsize=False)

c:\Users\Shenghui\anaconda3\Lib\site-packages\plotnine\ggplot.py:623: PlotnineWarning: Saving 6.4 x 4.8 in image.
c:\Users\Shenghui\anaconda3\Lib\site-packages\plotnine\ggplot.py:624: PlotnineWarning: Filename: ./Task2\img\GDP_regions.png

In [6]:
# Columns selection for crypto-currency datasets
mycols = ['Country Code']
yr = 2013
while yr < 2025:
    mycols.append(str(yr))
    yr += 1

In [7]:
## Inflation
df = pd.read_csv(
    base_path + r"\data\inflation.csv"
)
df_s = df.loc[:, mycols] # selecting only required columns
df_s = df_s[df_s['Country Code'].isin(myrows)]

df_s = df_s.reset_index(drop=True).T  # transpose
df_s = df_s.reset_index().rename(columns={'index': 'Year'}) # reset index and rename
df_s.columns = df_s.iloc[0] # set first row as header
df_s.rename(columns={'Country Code': 'Year'}, inplace=True) # rename column since transposing
df_s = df_s[1:]                                # remove first row since it is now header
df_s = df_s.apply(pd.to_numeric, errors='coerce')  # convert to numeric, coerce errors to NaN


df_inf_long = df_s.melt(id_vars='Year', var_name='Region', value_name='INF') # long format
years = df_s['Year'].tolist() # list of years for x-axis
p = (
    ggplot(df_inf_long, aes(x='Year', y='INF', color='Region'))
    + geom_line()
    + geom_point()
    + scale_color_manual(values=colors[:len(df_inf_long['Region'].unique())])
    + scale_x_continuous(breaks=years)
    + scale_y_continuous(labels=lambda l: [f"{v:.2e}" for v in l])
    + labs(title="Inflation for different regions", x="Year", y="Inflation")
    + theme(axis_text_x=element_text(rotation=45, ha='center'))
)
p.save(base_path + r"\img\Inflation_regions.png", dpi=300, limitsize=False)

c:\Users\Shenghui\anaconda3\Lib\site-packages\plotnine\ggplot.py:623: PlotnineWarning: Saving 6.4 x 4.8 in image.
c:\Users\Shenghui\anaconda3\Lib\site-packages\plotnine\ggplot.py:624: PlotnineWarning: Filename: ./Task2\img\Inflation_regions.png

In [8]:
## unemployment
df = pd.read_csv(
    base_path + r"\data\unemployment.csv"
)
df_s = df.loc[:, mycols]
df_s = df_s[df_s['Country Code'].isin(myrows)]

df_s = df_s.reset_index(drop=True).T 
df_s = df_s.reset_index().rename(columns={'index': 'Year'})
df_s.columns = df_s.iloc[0]
df_s.rename(columns={'Country Code': 'Year'}, inplace=True)
df_s = df_s[1:]
df_s = df_s.apply(pd.to_numeric, errors='coerce')


df_une_long = df_s.melt(id_vars='Year', var_name='Region', value_name='UNE')
years = df_s['Year'].tolist()
p = (
    ggplot(df_une_long, aes(x='Year', y='UNE', color='Region'))
    + geom_line()
    + geom_point()
    + scale_color_manual(values=colors[:len(df_une_long['Region'].unique())])
    + scale_x_continuous(breaks=years)
    + labs(title="Unemployment for different regions", x="Year", y="Unemployment rate %")
    + theme(axis_text_x=element_text(rotation=45, ha='center'))
)
p.save(base_path + r"\img\Unemployment_regions.png", dpi=300, limitsize=False)

c:\Users\Shenghui\anaconda3\Lib\site-packages\plotnine\ggplot.py:623: PlotnineWarning: Saving 6.4 x 4.8 in image.
c:\Users\Shenghui\anaconda3\Lib\site-packages\plotnine\ggplot.py:624: PlotnineWarning: Filename: ./Task2\img\Unemployment_regions.png

In [9]:
df_une_long

    Year Region       UNE
0   2013    EAS  4.038529
1   2014    EAS  4.017840
2   2015    EAS  4.082513
3   2016    EAS  3.995805
4   2017    EAS  3.865650
..   ...    ...       ...
91  2020    WLD  6.608997
92  2021    WLD  6.064327
93  2022    WLD  5.260660
94  2023    WLD  4.915919
95  2024    WLD  4.891450

[96 rows x 3 columns]

In [10]:
# Combine top 3 coins data from coinmarketcap and make them as yearly time series for correlation analysis
df_b = pd.read_csv(
    r".\Task1\data\Bitcoin_monthly_010413-011125.csv",
    sep=";"
)
df_b['timeOpen'] = pd.to_datetime(df_b['timeOpen'], utc=True).dt.tz_convert(None)           
df_b = df_b.sort_values('timeOpen', ascending=True).reset_index(drop=True)

df_e = pd.read_csv(
    r".\Task1\data\Ethereum_monthly_010915-011125.csv",
    sep=";"
)
df_e['timeOpen'] = pd.to_datetime(df_e['timeOpen'], utc=True).dt.tz_convert(None)             
df_e = df_e.sort_values('timeOpen', ascending=True).reset_index(drop=True)

df_t = pd.read_csv(
    r".\Task1\data\Tether_monthly_010315-011125.csv",
    sep=";"
)
df_t['timeOpen'] = pd.to_datetime(df_t['timeOpen'], utc=True).dt.tz_convert(None)                
df_t = df_t.sort_values('timeOpen', ascending=True).reset_index(drop=True)

convert_yearly = lambda df: (
                                df
                                .set_index("timeOpen")
                                .resample("Y")["volume"]
                                .sum()
                            )
b_v = convert_yearly(df_b)
e_v = convert_yearly(df_e)
t_v = convert_yearly(df_t)

df_yearly_total = (
    b_v
    .add(e_v, fill_value=0)
    .add(t_v, fill_value=0)
    .reset_index()
)
df_yearly_total["year"] = df_yearly_total["timeOpen"].dt.year
df_yearly_total = df_yearly_total[["year", "volume"]]
df_yearly_total.set_index("year", inplace=True)

C:\Users\Shenghui\AppData\Local\Temp\ipykernel_26000\2091122740.py:26: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.

In [ ]:
# Four dataframes created for correlation analysis:
#df_GDP_long    <= melted dataframe
#df_inf_long    <= melted dataframe
#df_une_long    <= melted dataframe
#df_yearly_total

In [11]:
df_GDP_long.set_index("Year", inplace=True)
df_inf_long.set_index("Year", inplace=True) 
df_une_long.set_index("Year", inplace=True)

In [16]:
df_GDP_long

     Region           GDP
Year
2013    EAS  2.165929e+13
2014    EAS  2.237221e+13
2015    EAS  2.229911e+13
2016    EAS  2.308967e+13
2017    EAS  2.465616e+13
...     ...           ...
2020    WLD  8.591276e+13
2021    WLD  9.814048e+13
2022    WLD  1.022515e+14
2023    WLD  1.067416e+14
2024    WLD  1.109827e+14

[96 rows x 2 columns]

In [12]:
gdp_region = {region : g['GDP'] for region,g in df_GDP_long.groupby('Region')}
inf_region = {region : g['INF'] for region,g in df_inf_long.groupby('Region')}
une_region = {region : g['UNE'] for region,g in df_une_long.groupby('Region')}

In [ ]:
# Function to compute and plot Two-Sided CCF Heatmap
import numpy as np
from statsmodels.tsa.stattools import ccf

lags_to_check = 2 
def ccf_heatmap_crypto_econ(df_yearly_total: pd.DataFrame, metrix_region: dict, lag_limit: int, title: str) -> pd.DataFrame: # Two-sided CCF heatmap for crypto and economic metric
    ccf_results = {} # Store CCF results for each region
    for region, metrix in metrix_region.items():
        # Align crypto and GDP on the intersection of their years
        crypto_s, metrix_aligned = df_yearly_total.align(metrix, join="inner", axis=0)
        
        #  Make Stationary (Log-Difference) conversion from raw values into "Growth Rates" (Percentage Change)
        crypto_st = np.log(crypto_s).diff().dropna()
        metrix_st = np.log(metrix_aligned).diff().dropna()
        
        # Re-align again just in case differencing created NaNs at edges
        crypto_st, metrix_st = crypto_st.align(metrix_st, join="inner", axis=0)
    

        # Compute Two-Sided CCF, adjusted=False to keep correlation between -1 & 1 and lag_limit + 1 because lag 0 is included
        # Forward: Crypto(t) vs GDP(t+k) -> "Does Crypto predict GDP?"
        forward = ccf(crypto_st, metrix_st, adjusted=False, nlags=lag_limit + 1)
        
        # Backward: GDP(t) vs Crypto(t+k) -> "Does GDP predict Crypto?"
        backward = ccf(metrix_st, crypto_st, adjusted=False, nlags=lag_limit + 1)
        
        # Combine into one array
        # Structure: [Backward(-2), Backward(-1), Lag 0, Forward(+1), Forward(+2)]
        # backward[1:][::-1] removes Lag 0 (duplicate) and reverses order
        full_ccf = np.concatenate([backward[1:][::-1], forward])
        ccf_results[region] = full_ccf

    # Create the index for the structure 
    lag_index = np.arange(-lag_limit, lag_limit + 1)

    # create DataFrame for the lagged CCF results
    ccf_df = pd.DataFrame(ccf_results, index=lag_index)
    
    # Melt for heatmap and ggplot it with number printed in the graph
    ccf_long = ccf_df.reset_index().rename(columns={"index": "lag"}).melt(id_vars="lag", var_name="Region", value_name="CCF")
    p = (
        ggplot(ccf_long, aes(x="Region", y="lag", fill="CCF"))
        + geom_tile(color="white")
        + geom_text(
            aes(label=ccf_long['CCF'].apply(lambda x: f"{x:.2f}")),
            size=8,        
            color="black"  
        )
        + scale_fill_gradient2(
            low="blue",
            mid="white",
            high="red",
            midpoint=0,
            name="CCF"
        )
        + scale_y_continuous(breaks=ccf_long['lag'].unique()) 
        + labs(
            title=title,
            x="Region",
            y="Lag"
        )
        + theme_minimal()
        + theme(
            figure_size=(10, 6)
        )
    )
    p.save(f"./Task2/img/{title.replace(' ', '_')}_Heatmap.png", dpi=300, limitsize=False)
    return ccf_df

In [ ]:
# Generate heatmaps for GDP, Inflation, and Unemployment against Crypto Volume
heatmap_gdp_vol = ccf_heatmap_crypto_econ(df_yearly_total, gdp_region, lags_to_check,"Cross-Correlation Function between GDP and Crypto Volume")
heatmap_inf_vol = ccf_heatmap_crypto_econ(df_yearly_total, inf_region, lags_to_check,"Cross-Correlation Function between Inflation and Crypto Volume")
heatmap_une_vol = ccf_heatmap_crypto_econ(df_yearly_total, une_region, lags_to_check,"Cross-Correlation Function between Unemployment and Crypto Volume")

c:\Users\19722\anaconda3\Lib\site-packages\plotnine\ggplot.py:623: PlotnineWarning: Saving 10 x 6 in image.
c:\Users\19722\anaconda3\Lib\site-packages\plotnine\ggplot.py:624: PlotnineWarning: Filename: ./Task2/img/Cross-Correlation_Function_between_GDP_and_Crypto_Volume_Heatmap.png
c:\Users\19722\anaconda3\Lib\site-packages\plotnine\ggplot.py:623: PlotnineWarning: Saving 10 x 6 in image.
c:\Users\19722\anaconda3\Lib\site-packages\plotnine\ggplot.py:624: PlotnineWarning: Filename: ./Task2/img/Cross-Correlation_Function_between_Inflation_and_Crypto_Volume_Heatmap.png
c:\Users\19722\anaconda3\Lib\site-packages\plotnine\ggplot.py:623: PlotnineWarning: Saving 10 x 6 in image.
c:\Users\19722\anaconda3\Lib\site-packages\plotnine\ggplot.py:624: PlotnineWarning: Filename: ./Task2/img/Cross-Correlation_Function_between_Unemployment_and_Crypto_Volume_Heatmap.png